=== outermedia/solr-fusion/src/main/resources/configuration.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" version="1.0" targetNamespace="http://solrfusion.outermedia.org/configuration/" xmlns:tns="http://solrfusion.outermedia.org/configuration/" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:import schemaLocation="schema2.xsd"/>

  <xs:element name="core">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fusion-schema-fields" type="tns:fusionSchemaFields"/>
        <xs:element name="script-type" type="tns:scriptType" maxOccurs="unbounded"/>
        <xs:element name="default-search-field" type="xs:string"/>
        <xs:element name="default-sort-field" type="xs:string"/>
        <xs:element name="default-operator" type="xs:string"/>
        <xs:element name="id-generator" type="tns:idGenerator"/>
        <xs:element name="response-consolidator" type="tns:response-consolidator"/>
        <xs:element name="response-mapper" type="tns:responseMapper"/>
        <xs:element name="query-mapper" type="tns:queryMapper"/>
        <xs:element name="controller" type="tns:controller"/>
        <xs:element name="solr-servers" type="tns:globalSearchServerConfig"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="mergeTarget">
    <xs:sequence/>
    <xs:attribute name="prio" type="xs:int" use="required"/>
    <xs:attribute name="target-name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="response-consolidator">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="util">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="fieldType">
    <xs:sequence/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="xs:string"/>
    <xs:attribute name="format" type="xs:string"/>
    <xs:attribute name="multi-value" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="changeOperation">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="query" type="tns:query"/>
        <xs:element name="response" type="tns:response"/>
        <xs:element name="query-response" type="tns:queryResponse"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="query">
    <xs:sequence>
      <xs:any processContents="skip" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:IDREF"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="fusion-name" type="xs:string"/>
    <xs:attribute name="target" type="tns:queryTarget"/>
  </xs:complexType>

  <xs:complexType name="scriptType">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="name" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:complexType name="response">
    <xs:sequence>
      <xs:any processContents="skip" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:IDREF"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="fusion-name" type="xs:string"/>
    <xs:attribute name="target" type="tns:responseTarget"/>
  </xs:complexType>

  <xs:complexType name="queryResponse">
    <xs:sequence>
      <xs:any processContents="skip" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:IDREF"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="fusion-name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="globalSearchServerConfig">
    <xs:sequence>
      <xs:element name="timeout" type="xs:int"/>
      <xs:element name="disaster-limit" type="xs:int"/>
      <xs:element name="error" type="tns:message"/>
      <xs:element name="page-size" type="xs:int"/>
      <xs:element name="query-parser" type="tns:queryParser"/>
      <xs:element name="dismax-query-parser" type="tns:queryParser"/>
      <xs:element name="response-parser" type="tns:responseParser"/>
      <xs:element name="response-renderer" type="tns:responseRenderer" maxOccurs="unbounded"/>
      <xs:element name="query-builder" type="tns:queryBuilder"/>
      <xs:element name="dismax-query-builder" type="tns:queryBuilder"/>
      <xs:element name="merge" type="tns:merge" minOccurs="0"/>
      <xs:element name="solr-server" type="tns:searchServerConfig" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="message">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="key" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="queryParser">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="responseParser">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="responseRenderer">
    <xs:sequence>
      <xs:any processContents="skip" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="type" type="tns:responseRendererType" use="required"/>
  </xs:complexType>

  <xs:complexType name="queryBuilder">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="merge">
    <xs:sequence>
      <xs:element name="target" type="tns:mergeTarget" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="fusion-name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="searchServerConfig">
    <xs:sequence>
      <xs:element name="config" type="tns:adapterConfig" minOccurs="0"/>
      <xs:element name="url" type="xs:string"/>
      <xs:element name="score" type="tns:scoreFactory"/>
      <xs:element name="response-parser" type="tns:responseParser" minOccurs="0"/>
      <xs:element name="query-builder" type="tns:queryBuilder" minOccurs="0"/>
      <xs:element name="unique-key" type="xs:string"/>
      <xs:element name="max-docs" type="xs:int"/>
      <xs:element name="field" type="tns:fieldMapping" maxOccurs="unbounded"/>
      <xs:element name="post-processor" type="tns:postProcessor" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="query-param-name" type="xs:string"/>
    <xs:attribute name="version" type="xs:string" use="required"/>
    <xs:attribute name="enabled" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="postProcessor">
    <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="query" type="tns:query"/>
            <xs:element name="response" type="tns:response"/>
            <xs:element name="query-response" type="tns:queryResponse"/>
        </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="adapterConfig">
    <xs:sequence>
      <xs:any processContents="skip" namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="scoreFactory">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="factor" type="xs:double" use="required"/>
  </xs:complexType>

  <xs:complexType name="fieldMapping">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="add" type="tns:addOperation"/>
        <xs:element name="drop" type="tns:dropOperation"/>
        <xs:element name="change" type="tns:changeOperation"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="fusion-name" type="xs:string"/>
    <xs:attribute name="name-pattern" type="xs:string"/>
    <xs:attribute name="fusion-name-replacement" type="xs:string"/>
    <xs:attribute name="name-replacement" type="xs:string"/>
    <xs:attribute name="fusion-name-pattern" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="addOperation">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="query" type="tns:query"/>
        <xs:element name="response" type="tns:response"/>
        <xs:element name="query-response" type="tns:queryResponse"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="level" type="tns:addLevel"/>
  </xs:complexType>

  <xs:complexType name="dropOperation">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="query" type="tns:query"/>
        <xs:element name="response" type="tns:response"/>
        <xs:element name="query-response" type="tns:queryResponse"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="targetsOfMapping">
    <xs:complexContent>
      <xs:extension base="arrayList">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="applicableResult">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="xmlValidationHandler">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="controller">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="responseMapper">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="ignore-missing-mappings" type="xs:boolean"/>
  </xs:complexType>

  <xs:complexType name="queryMapper">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="fusionSchemaFields">
    <xs:sequence>
      <xs:element name="field" type="tns:fieldType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="default-type" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="idGenerator">
    <xs:sequence/>
    <xs:attribute name="class" type="xs:string" use="required"/>
    <xs:attribute name="fusion-name" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:simpleType name="queryTarget">
    <xs:restriction base="xs:string">
      <xs:enumeration value="highlight-query"/>
      <xs:enumeration value="filter-query"/>
      <xs:enumeration value="all"/>
      <xs:enumeration value="query"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="responseTarget">
    <xs:restriction base="xs:string">
      <xs:enumeration value="highlight"/>
      <xs:enumeration value="all"/>
      <xs:enumeration value="document"/>
      <xs:enumeration value="facet"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="responseRendererType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="php"/>
        <xs:enumeration value="json"/>
        <xs:enumeration value="xml"/>
        <xs:enumeration value="javabin"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="addLevel">
    <xs:restriction base="xs:string">
      <xs:enumeration value="inside"/>
      <xs:enumeration value="outside"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== outermedia/solr-fusion/src/test/resources/test-fusion-schema-embedder-solr-adapter.xml
<?xml version="1.0" encoding="UTF-8"?>
<om:core xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:om="http://solrfusion.outermedia.org/configuration/"
    xmlns="http://solrfusion.outermedia.org/configuration/type/"
    xsi:schemaLocation="http://solrfusion.outermedia.org/configuration/ ../../main/resources/configuration.xsd ">

    <om:fusion-schema-fields default-type="text">
        <om:field name="id" />
        <om:field name="language" />
        <om:field name="title" />
        <om:field name="score" type="float" />
    </om:fusion-schema-fields>

    <om:script-type name="javascript" class="org.outermedia.solrfusion.types.Js" />
    <om:script-type name="beanshell" class="org.outermedia.solrfusion.types.Bsh" />

    <om:default-search-field>title</om:default-search-field>

    <om:default-sort-field>score desc</om:default-sort-field>
    
    <om:default-operator>AND</om:default-operator>

    <om:id-generator fusion-name="id"
        class="org.outermedia.solrfusion.DefaultIdGenerator$Factory" />

    <om:response-consolidator class="org.outermedia.solrfusion.response.PagingResponseConsolidator$Factory"/>

    <om:response-mapper class="org.outermedia.solrfusion.mapper.ResponseMapper$Factory" />

    <om:query-mapper class="org.outermedia.solrfusion.mapper.QueryMapper$Factory" />

    <om:controller class="org.outermedia.solrfusion.FusionController$Factory" />

    <om:ids-controller class="org.outermedia.solrfusion.IdsFusionController$Factory" />

    <om:solr-servers>
        <om:timeout>4000</om:timeout>
        <om:disaster-limit>2</om:disaster-limit>
        <om:error key="disaster-limit">Please try later again.</om:error>
        <om:page-size>10</om:page-size>
        
        <om:query-parser
            class="org.outermedia.solrfusion.query.EdisMaxQueryParser$Factory" />

        <om:dismax-query-parser
            class="org.outermedia.solrfusion.query.DisMaxQueryParser$Factory"/>

        <om:response-parser
            class="org.outermedia.solrfusion.response.DefaultResponseParser$Factory" />

        <om:response-renderer type="xml"
            class="org.outermedia.solrfusion.response.DefaultXmlResponseRenderer$Factory" >
            <map-type fusion-type="float" key="float"/>
            <map-type fusion-type="double" key="float"/>
            <map-type fusion-type="int" key="int"/>
            <map-type fusion-type="long" key="int"/>
            <map-type fusion-type="boolean" key="bool"/>
            <map-type fusion-type="date" key="date"/>
            <map-type fusion-type="text" key="str"/>
            <map-multi-value-type key="arr"/>
        </om:response-renderer>

        <om:response-renderer type="json"
            class="org.outermedia.solrfusion.response.DefaultJsonResponseRenderer$Factory" />

        <om:response-renderer type="php"
            class="org.outermedia.solrfusion.response.DefaultPhpResponseRenderer$Factory" />

        <om:query-builder class="org.outermedia.solrfusion.mapper.QueryBuilder$Factory"/>

        <om:dismax-query-builder class="org.outermedia.solrfusion.mapper.DisMaxQueryBuilder$Factory"/>

        <om:solr-server name="Bibliothek9000" version="3.6"
            class="org.outermedia.solrfusion.adapter.solr.EmbeddedSolrAdapter$Factory">
            <om:config>
                <solr-home>src/test/resources/solr/solr-home-1</solr-home>
            </om:config>

            <om:url>src/test/resources/solr/solr-home-1</om:url>

            <om:score factor="1.2"
                class="org.outermedia.solrfusion.DefaultScore$Factory" />

            <om:unique-key>id</om:unique-key>

            <om:max-docs>100</om:max-docs>

            <om:field name="title" fusion-name="title" />
            <om:field name="language" fusion-name="language" />

        </om:solr-server>

        <om:solr-server name="Bibliothek9002" version="3.6"
                        class="org.outermedia.solrfusion.adapter.solr.EmbeddedSolrAdapter$Factory">
            <om:config>
                <solr-home>src/test/resources/solr/solr-home-2</solr-home>
            </om:config>

            <om:url>src/test/resources/solr/solr-home-2</om:url>

            <om:score factor="2.2"
                      class="org.outermedia.solrfusion.DefaultScore$Factory" />

            <om:unique-key>id</om:unique-key>

            <om:max-docs>100</om:max-docs>

            <om:field name="titleVT_de" fusion-name="title" />
            <om:field name="titleVT_eng" fusion-name="title" />
            <om:field name="language" fusion-name="language" />

        </om:solr-server>

    </om:solr-servers>
</om:core>

=== outermedia/solr-fusion/src/test/resources/test-doc-merging-fusion-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<om:core xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:om="http://solrfusion.outermedia.org/configuration/"
    xmlns="http://solrfusion.outermedia.org/configuration/type/"
    xsi:schemaLocation="http://solrfusion.outermedia.org/configuration/ ../../main/resources/configuration.xsd ">

    <om:fusion-schema-fields default-type="text">
        <om:field name="id"/>
        <om:field name="title"/>
        <om:field name="score" type="double"/>
        <om:field name="isbn" multi-value="true"/>
        <om:field name="author"/>
        <om:field name="other1"/>
        <om:field name="other2"/>
        <om:field name="other3"/>
    </om:fusion-schema-fields>

    <om:script-type name="javascript-file" class="org.outermedia.solrfusion.types.JsFile"/>
    <om:script-type name="beanshell-file" class="org.outermedia.solrfusion.types.BshFile"/>
    <om:script-type name="javascript" class="org.outermedia.solrfusion.types.Js"/>
    <om:script-type name="beanshell" class="org.outermedia.solrfusion.types.Bsh"/>
    <om:script-type name="java-class" class="org.outermedia.solrfusion.types.Java"/>
    <om:script-type name="regexp" class="org.outermedia.solrfusion.types.RegularExpression"/>
    <om:script-type name="static-table-file" class="org.outermedia.solrfusion.types.TableFile"/>
    <om:script-type name="static-table" class="org.outermedia.solrfusion.types.Table"/>
    <om:script-type name="static-value" class="org.outermedia.solrfusion.types.Value"/>
    <om:script-type name="merge-multi-value" class="org.outermedia.solrfusion.types.MultiValueMerger"/>

    <om:default-search-field>title</om:default-search-field>

    <om:default-sort-field>score desc</om:default-sort-field>

    <om:default-operator>AND</om:default-operator>

    <om:id-generator fusion-name="id"
        class="org.outermedia.solrfusion.DefaultIdGenerator$Factory"/>

    <om:response-consolidator class="org.outermedia.solrfusion.response.PagingResponseConsolidator$Factory"/>

    <om:response-mapper class="org.outermedia.solrfusion.mapper.ResponseMapper$Factory"/>

    <om:query-mapper class="org.outermedia.solrfusion.mapper.QueryMapper$Factory"/>


    <om:controller class="org.outermedia.solrfusion.FusionController$Factory"/>

    <om:ids-controller class="org.outermedia.solrfusion.IdsFusionController$Factory" />

    <om:solr-servers>
        <om:timeout>4000</om:timeout>
        <om:disaster-limit>1</om:disaster-limit>
        <om:error key="disaster-limit">Please try later again.</om:error>

        <om:query-parser
            class="org.outermedia.solrfusion.query.EdisMaxQueryParser$Factory"/>

        <om:dismax-query-parser
            class="org.outermedia.solrfusion.query.DisMaxQueryParser$Factory"/>

        <om:response-parser
            class="org.outermedia.solrfusion.response.DefaultResponseParser$Factory"/>

        <om:response-renderer type="xml"
            class="org.outermedia.solrfusion.response.DefaultXmlResponseRenderer$Factory" >
        </om:response-renderer>

        <om:query-builder class="org.outermedia.solrfusion.mapper.QueryBuilder$Factory"/>

        <om:dismax-query-builder class="org.outermedia.solrfusion.mapper.DisMaxQueryBuilder$Factory"/>

        <om:merge fusion-name="isbn"
            class="org.outermedia.solrfusion.DefaultMergeStrategy$Factory">
            <om:target prio="200" target-name="BibliothekD"/>
            <om:target prio="1" target-name="BibliothekA"/>
            <om:target prio="3" target-name="BibliothekC"/>
            <om:target prio="2" target-name="BibliothekB"/>
        </om:merge>

        <om:solr-server name="BibliothekA" version="3.6"
            class="org.outermedia.solrfusion.adapter.solr.DefaultSolrAdapter$Factory">

            <om:url>http://host:port/solr/xyz</om:url>

            <om:score factor="1.2"
                class="org.outermedia.solrfusion.DefaultScore$Factory"/>

            <om:unique-key>Id</om:unique-key>

            <om:max-docs>100</om:max-docs>

            <om:field name="Id" fusion-name="id"/>
            <om:field name="Title" fusion-name="title"/>
            <om:field name="ISBN" fusion-name="isbn"/>
            <om:field name="Author" fusion-name="author"/>
            <om:field name="Other1" fusion-name="other1"/>
            <om:field name="Other2" fusion-name="other2"/>
            <om:field name="Other3" fusion-name="other3"/>
        </om:solr-server>

        <om:solr-server name="BibliothekB" version="3.6"
            class="org.outermedia.solrfusion.adapter.solr.DefaultSolrAdapter$Factory">

            <om:url>http://host:port/solr/xyz</om:url>

            <om:score factor="1.2"
                class="org.outermedia.solrfusion.DefaultScore$Factory"/>

            <om:unique-key>Id</om:unique-key>

            <om:max-docs>100</om:max-docs>

            <om:field name="Id" fusion-name="id"/>
            <om:field name="Title" fusion-name="title"/>
            <om:field name="ISBN" fusion-name="isbn"/>
            <om:field name="Author" fusion-name="author"/>
            <om:field name="Other1" fusion-name="other1"/>
            <om:field name="Other2" fusion-name="other2"/>
            <om:field name="Other3" fusion-name="other3"/>
        </om:solr-server>

        <om:solr-server name="BibliothekC" version="3.6"
            class="org.outermedia.solrfusion.adapter.solr.DefaultSolrAdapter$Factory">

            <om:url>http://host:port/solr/xyz</om:url>

            <om:score factor="1.2"
                class="org.outermedia.solrfusion.DefaultScore$Factory"/>

            <om:unique-key>Id</om:unique-key>

            <om:max-docs>100</om:max-docs>

            <om:field name="Id" fusion-name="id"/>
            <om:field name="Title" fusion-name="title"/>
            <om:field name="ISBN" fusion-name="isbn"/>
            <om:field name="Author" fusion-name="author"/>
            <om:field name="Other1" fusion-name="other1"/>
            <om:field name="Other2" fusion-name="other2"/>
            <om:field name="Other3" fusion-name="other3"/>
            <om:field name="Unknown">
                <om:drop>
                    <om:response />
                </om:drop>
            </om:field>
        </om:solr-server>

        <om:solr-server name="BibliothekD" version="3.6"
            class="org.outermedia.solrfusion.adapter.solr.DefaultSolrAdapter$Factory">

            <om:url>http://host:port/solr/xyz</om:url>

            <om:score factor="1.2"
                class="org.outermedia.solrfusion.DefaultScore$Factory"/>

            <om:unique-key>Id</om:unique-key>

            <om:max-docs>100</om:max-docs>

            <om:field name="Id" fusion-name="id"/>
            <om:field name="Title" fusion-name="title"/>
            <om:field name="ISBN" fusion-name="isbn"/>
            <om:field name="Author" fusion-name="author"/>
            <om:field name="Other1" fusion-name="other1"/>
            <om:field name="Other2" fusion-name="other2"/>
            <om:field name="Other3" fusion-name="other3"/>
        </om:solr-server>

    </om:solr-servers>
</om:core>

=== outermedia/solr-fusion/src/test/resources/test-query-mapper-fusion-schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<om:core xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:om="http://solrfusion.outermedia.org/configuration/"
    xmlns="http://solrfusion.outermedia.org/configuration/type/"
    xsi:schemaLocation="http://solrfusion.outermedia.org/configuration/ ../../main/resources/configuration.xsd ">

    <om:fusion-schema-fields default-type="text">
        <om:field name="id"/>
        <om:field name="author"/>
        <om:field name="title"/>
        <om:field name="score" type="double"/>
        <om:field name="valueFrom7" />
    </om:fusion-schema-fields>

    <om:script-type name="javascript" class="org.outermedia.solrfusion.types.Js"/>
    <om:script-type name="beanshell" class="org.outermedia.solrfusion.types.Bsh"/>

    <om:default-search-field>title</om:default-search-field>

    <om:default-sort-field>score desc</om:default-sort-field>

    <om:default-operator>AND</om:default-operator>

    <om:id-generator fusion-name="id"
        class="org.outermedia.solrfusion.DefaultIdGenerator$Factory"/>

    <om:response-consolidator class="org.outermedia.solrfusion.response.PagingResponseConsolidator$Factory"/>

    <om:response-mapper class="org.outermedia.solrfusion.mapper.ResponseMapper$Factory"/>

    <om:query-mapper class="org.outermedia.solrfusion.mapper.QueryMapper$Factory"/>

    <om:controller class="org.outermedia.solrfusion.FusionController$Factory"/>

    <om:ids-controller class="org.outermedia.solrfusion.IdsFusionController$Factory" />

    <om:solr-servers>
        <om:timeout>4000</om:timeout>
        <om:disaster-limit>1</om:disaster-limit>
        <om:error key="disaster-limit">Please try later again.</om:error>
        <om:page-size>10</om:page-size>

        <om:query-parser
            class="org.outermedia.solrfusion.query.EdisMaxQueryParser$Factory"/>

        <om:dismax-query-parser
            class="org.outermedia.solrfusion.query.DisMaxQueryParser$Factory"/>

        <om:response-parser
            class="org.outermedia.solrfusion.response.DefaultResponseParser$Factory"/>

        <om:response-renderer type="xml"
            class="org.outermedia.solrfusion.response.DefaultXmlResponseRenderer$Factory"/>

        <om:response-renderer type="json"
            class="org.outermedia.solrfusion.response.DefaultJsonResponseRenderer$Factory"/>

        <om:response-renderer type="php"
            class="org.outermedia.solrfusion.response.DefaultPhpResponseRenderer$Factory"/>

        <om:query-builder class="org.outermedia.solrfusion.mapper.QueryBuilder$Factory"/>

        <om:dismax-query-builder class="org.outermedia.solrfusion.mapper.DisMaxQueryBuilder$Factory"/>

        <om:solr-server name="BibliothekA" version="3.6"
            class="org.outermedia.solrfusion.adapter.solr.DefaultSolrAdapter$Factory">

            <om:url>http://host:port/solr/xyz</om:url>

            <om:score factor="1.2"
                class="org.outermedia.solrfusion.DefaultScore$Factory"/>

            <om:unique-key>id</om:unique-key>

            <om:max-docs>100</om:max-docs>

            <om:field name="id" fusion-name="id"/>
            <om:field name="Titel" fusion-name="title"/>
            <om:field name="Autor" fusion-name="author"/>

            <om:field
                name-pattern="val([0-9]+)Start" fusion-name-replacement="valueFrom$1"
                name-replacement="val$1Start" fusion-name-pattern="valueFrom([0-9]+)"
                />

        </om:solr-server>

        <!-- more solr servers definitions ... -->

    </om:solr-servers>
</om:core>
